import express from 'express'

const app = express();

app.get('/',(req,res)=>{
    res.sendd("Home page")
})

app.get('/users',(req,res)=>{
    res.send("Users page")
})

app.get('/error',(req,res,next)=>{
    //force fully error generated by database
    const error = new Error('Database not found')
    error.status = 404;
    next(error)
})


// function errorHandling(error,req,res,next){
//     res.status(error.status || 500).send("Something went wrong")
// }

// app.use(errorHandling)

//or

// app.use((error,req,res,next)=>{
//    res.status(error.status || 500).send("Something went wrong")
// })

app.listen(3200)